version: '3.7'

services:
  mariadb:
    image: mariadb:10.7
    restart: always
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD:  password
      MYSQL_DATABASE: monitoringdb
